In [1]:
import pandas as pd

print(pd.__version__)

3.0.0

In [14]:
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a)

print(myvar)

0    1
1    7
2    2
dtype: int64

In [27]:
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a, index = ["x", "y", "z"])

print(myvar)

x    1
y    7
z    2
dtype: int64

In [40]:
import pandas as pd
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)
print(df)

   calories  duration
0       420        50
1       380        40
2       390        45

In [41]:
import pandas as pd
data = {
    "Name": ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    "Age": [25, 30, 35, 40, 45],
    "City": ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'],
    "Salary": [70000, 80000, 90000, 100000, 110000]
}
df = pd.DataFrame(data)
print("DataFrame created from the dictionary:")
print(df)

DataFrame created from the dictionary:
      Name  Age         City  Salary
0    Alice   25     New York   70000
1      Bob   30  Los Angeles   80000
2  Charlie   35      Chicago   90000
3    David   40      Houston  100000
4      Eve   45      Phoenix  110000

In [42]:
column = df['Age']  # Accessing the 'Age' column
df.to_csv('output.csv' , index=False) # This line saves the DataFrame to a CSV file named 'output.csv' without including the index column.

In [43]:
print("Descriptive statistics of the DataFrame:")
print(df.describe())

Descriptive statistics of the DataFrame:
             Age         Salary
count   5.000000       5.000000
mean   35.000000   90000.000000
std     7.905694   15811.388301
min    25.000000   70000.000000
25%    30.000000   80000.000000
50%    35.000000   90000.000000
75%    40.000000  100000.000000
max    45.000000  110000.000000

In [44]:
print(f'Shape of the DataFrame: {df.shape}')
print(f'Columns in the DataFrame: {df.columns}')

Shape of the DataFrame: (5, 4)
Columns in the DataFrame: Index(['Name', 'Age', 'City', 'Salary'], dtype='str')

In [45]:
print("Name (single column):")
print(df["Name"])

Name (single column):
0      Alice
1        Bob
2    Charlie
3      David
4        Eve
Name: Name, dtype: str

In [46]:
#selecting multiple columns
print("Name and City (multiple columns):")
subset = df[["Name", "City"]]
print(subset)

Name and City (multiple columns):
      Name         City
0    Alice     New York
1      Bob  Los Angeles
2  Charlie      Chicago
3    David      Houston
4      Eve      Phoenix

In [47]:
#High Salary
high_salary = df[df["Salary"] > 90000]
print(high_salary)

    Name  Age     City  Salary
3  David   40  Houston  100000
4    Eve   45  Phoenix  110000

In [48]:
#filtering rows based on multiple conditions
filtered_data = df[(df["Age"] > 30) & (df["Salary"] > 90000)]
print("Filtered data (Age > 30 and Salary > 90000):")
print(filtered_data)

Filtered data (Age > 30 and Salary > 90000):
    Name  Age     City  Salary
3  David   40  Houston  100000
4    Eve   45  Phoenix  110000

In [49]:
#adding new column
df["Bonus"] = df["Salary"] * 0.1  # Adding a new column 'Bonus' which is 10% of the Salary
print(df)

      Name  Age         City  Salary    Bonus
0    Alice   25     New York   70000   7000.0
1      Bob   30  Los Angeles   80000   8000.0
2  Charlie   35      Chicago   90000   9000.0
3    David   40      Houston  100000  10000.0
4      Eve   45      Phoenix  110000  11000.0

In [50]:
#inserting a new column at a specific position
df.insert(2, "Department", ["HR", "IT", "Finance", "Marketing", "Sales"])  # Inserting 'Department' column at index 2
print(df)

      Name  Age Department         City  Salary    Bonus
0    Alice   25         HR     New York   70000   7000.0
1      Bob   30         IT  Los Angeles   80000   8000.0
2  Charlie   35    Finance      Chicago   90000   9000.0
3    David   40  Marketing      Houston  100000  10000.0
4      Eve   45      Sales      Phoenix  110000  11000.0

In [51]:
#updating values in a column
df.loc[0, "Salary"] = 75000  # Updating the salary of the first row to 75000    
print(df)

      Name  Age Department         City  Salary    Bonus
0    Alice   25         HR     New York   75000   7000.0
1      Bob   30         IT  Los Angeles   80000   8000.0
2  Charlie   35    Finance      Chicago   90000   9000.0
3    David   40  Marketing      Houston  100000  10000.0
4      Eve   45      Sales      Phoenix  110000  11000.0

In [52]:
#increasing salary by 5% for all employees
df["Salary"] = df["Salary"] * 1.05  # Increasing salary by 5% for all employees
print(df)

      Name  Age Department         City    Salary    Bonus
0    Alice   25         HR     New York   78750.0   7000.0
1      Bob   30         IT  Los Angeles   84000.0   8000.0
2  Charlie   35    Finance      Chicago   94500.0   9000.0
3    David   40  Marketing      Houston  105000.0  10000.0
4      Eve   45      Sales      Phoenix  115500.0  11000.0

In [54]:
#Selecting Subsets of Rows and Columns
df.loc[[0,1]][["City","Salary"]]

          City   Salary
0     New York  78750.0
1  Los Angeles  84000.0

In [56]:
df[df["Age"] > 30]

      Name  Age Department     City    Salary    Bonus
2  Charlie   35    Finance  Chicago   94500.0   9000.0
3    David   40  Marketing  Houston  105000.0  10000.0
4      Eve   45      Sales  Phoenix  115500.0  11000.0